### ISSUE TITLE
training data depth map

### ISSUE THREAD

**Issue by xjturobocon** [sfu-gruvi-3dv/deep_human#2]
Hey,
Thanks for your sharing, good job!
I found in the training dataset you provide, the folder 'old/3/', the depth info is in the format '.npy', the maxium depth is often 0.6, and the minimum number is negtive. the visualiztion of it shows it is very coarse in the part of torso. However, in the demo data, the maxium depth is bigger than 2, and all numbers aer positive. The visulization result is also finer than the train data.

Hope for your kindly explanation.

**Comment by sta105** [comment]
The depth files in the folder 'old/3/' are actually pre-processed, we will re-upload our raw dataset. Thanks for reminding us.
